# Generated by Django 4.0.1 on 2022-01-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('track_id', models.IntegerField(verbose_name='track_id')),
                ('rating', models.IntegerField(verbose_name='rating')),
            ],
        ),
    ]
